ci:
    autofix_commit_msg: 'style: pre-commit auto fixes'
    autofix_prs: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
